'use client';

import { useState, useEffect, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { trpc } from '@/lib/trpc/trpc';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  Sparkles, 
  User, 
  Building2, 
  TrendingUp, 
  X, 
  CheckCircle2,
  Loader2,
  AlertCircle,
  RefreshCw,
  Clock
} from 'lucide-react';
import { toast } from 'sonner';
import { MentorRecommendationCard } from './MentorRecommendationCard';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';

interface RecommendedMentorsCardProps {
  onDismiss?: () => void;
}

export function RecommendedMentorsCard({ onDismiss }: RecommendedMentorsCardProps) {
  const router = useRouter();
  const [selectedMentorId, setSelectedMentorId] = useState<string | null>(null);
  const [showConfirmDialog, setShowConfirmDialog] = useState(false);

  // Track if we've already attempted auto-generation
  const hasAutoGenerated = useRef(false);

  // Fetch recommendations
  const { 
    data: recommendations, 
    isLoading, 
    refetch 
  } = trpc.mentorship.getRecommendedMentors.useQuery(undefined, {
    refetchOnWindowFocus: false,
    retry: 2,
  });

  // Mutations
  const acceptMutation = trpc.mentorship.acceptRecommendation.useMutation({
    onSuccess: () => {
      toast.success('Recommendation accepted! We\'ll notify the mentor.');
      router.push('/mentorship/dashboard');
    },
    onError: (error) => {
      toast.error(`Failed to accept recommendation: ${error.message}`);
    },
  });

  const dismissMutation = trpc.mentorship.dismissRecommendation.useMutation({
    onSuccess: () => {
      toast.success('Recommendation dismissed');
      onDismiss?.();
      refetch();
    },
    onError: (error) => {
      toast.error(`Failed to dismiss recommendation: ${error.message}`);
    },
  });

  const generateMutation = trpc.mentorship.generateRecommendations.useMutation({
    onSuccess: () => {
      // Silent success for auto-generation - refetch will show results
      setTimeout(() => {
        refetch();
      }, 2000);
    },
    onError: (error) => {
      // Silent error for auto-generation - will show button as fallback
      console.warn('Auto-generation failed:', error.message);
    },
  });

  // Auto-generate recommendations when component loads and no recommendations exist
  useEffect(() => {
    // Only auto-generate once, and only if:
    // 1. Not currently loading recommendations
    // 2. No recommendations exist
    // 3. Haven't already attempted auto-generation
    // 4. Not currently generating
    if (
      !isLoading &&
      !recommendations &&
      !hasAutoGenerated.current &&
      !generateMutation.isPending
    ) {
      hasAutoGenerated.current = true;
      // Auto-generate in the background - no button click needed!
      generateMutation.mutate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isLoading, recommendations]);

  const handleAccept = (mentorId: string) => {
    if (!recommendations?.id) return;
    
    setSelectedMentorId(mentorId);
    setShowConfirmDialog(true);
  };

  const confirmAccept = () => {
    if (!selectedMentorId || !recommendations?.id) return;
    
    acceptMutation.mutate({
      recommendation_id: recommendations.id,
      mentor_id: selectedMentorId,
    });
    
    setShowConfirmDialog(false);
  };

  const handleDismiss = () => {
    if (!recommendations?.id) return;
    
    if (confirm('Are you sure you want to dismiss these recommendations?')) {
      dismissMutation.mutate({
        recommendation_id: recommendations.id,
      });
    }
  };

  const handleGenerate = () => {
    generateMutation.mutate();
  };

  // Loading state - show while fetching OR auto-generating
  if (isLoading || (generateMutation.isPending && !recommendations)) {
    return (
      <Card className="border-primary bg-primary/5">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5" />
            Recommended Mentors
          </CardTitle>
          <CardDescription>
            {generateMutation.isPending 
              ? 'Generating personalized recommendations for you...' 
              : 'Finding perfect mentors for you...'}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-center py-8">
            <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
          </div>
        </CardContent>
      </Card>
    );
  }

  // No recommendations state - show after auto-generation attempt
  if (!recommendations) {
    return (
      <Card className="border-primary bg-primary/5">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5" />
            Recommended Mentors
          </CardTitle>
          <CardDescription>We&apos;ll find great mentors based on your profile</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="text-center py-6 space-y-4">
            <AlertCircle className="h-12 w-12 text-muted-foreground mx-auto" />
            <p className="text-sm text-muted-foreground">
              {generateMutation.isError
                ? 'We couldn\'t generate recommendations right now. Please try again or complete your profile with more details.'
                : 'No recommendations available yet. Please complete your profile or try generating manually.'}
            </p>
            <Button 
              onClick={handleGenerate} 
              disabled={generateMutation.isPending}
              variant="outline"
            >
              {generateMutation.isPending ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <RefreshCw className="h-4 w-4 mr-2" />
                  Try Generating Recommendations
                </>
              )}
            </Button>
          </div>
        </CardContent>
      </Card>
    );
  }

  // Has recommendations
  const { mentors } = recommendations;

  if (!mentors || mentors.length === 0) {
    return (
      <Card className="border-primary bg-primary/5">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5" />
            Recommended Mentors
          </CardTitle>
          <CardDescription>No mentors available at this time</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="text-center py-6">
            <p className="text-sm text-muted-foreground mb-4">
              We couldn&apos;t find available mentors. Try again later or request a mentor manually.
            </p>
            <Button 
              onClick={handleGenerate} 
              disabled={generateMutation.isPending}
              variant="outline"
            >
              {generateMutation.isPending ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <RefreshCw className="h-4 w-4 mr-2" />
                  Try Again
                </>
              )}
            </Button>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <>
      <Card className="border-primary bg-primary/5">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <Sparkles className="h-5 w-5" />
                Recommended Mentors For You
              </CardTitle>
              <CardDescription>
                Based on your profile, we found {mentors.length} great {mentors.length === 1 ? 'match' : 'matches'}!
              </CardDescription>
            </div>
            <Button
              variant="ghost"
              size="sm"
              onClick={handleDismiss}
              disabled={dismissMutation.isPending}
              className="h-8 w-8 p-0"
              title="Dismiss recommendations"
            >
              <X className="h-4 w-4" />
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {/* Display mentors */}
            {mentors.map((mentor, index) => (
              <MentorRecommendationCard
                key={mentor.id}
                mentor={mentor}
                rank={index + 1}
                onSelect={() => handleAccept(mentor.id)}
                isLoading={acceptMutation.isPending && selectedMentorId === mentor.id}
              />
            ))}

            {/* Expiration notice */}
            {recommendations.expires_at && (
              <div className="text-xs text-muted-foreground pt-2 border-t">
                <Clock className="h-3 w-3 inline mr-1" />
                Recommendations expire on {new Date(recommendations.expires_at).toLocaleDateString()}
              </div>
            )}

            {/* Alternative action */}
            <div className="pt-2 border-t">
              <Button
                variant="outline"
                className="w-full"
                onClick={() => router.push('/mentorship/dashboard')}
              >
                Request Different Mentor
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Confirmation Dialog */}
      <Dialog open={showConfirmDialog} onOpenChange={setShowConfirmDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Accept Recommendation?</DialogTitle>
            <DialogDescription>
              Are you sure you want to accept this mentor recommendation? We&apos;ll notify them and they can choose to work with you.
            </DialogDescription>
          </DialogHeader>
          <div className="flex gap-2 justify-end mt-4">
            <Button
              variant="outline"
              onClick={() => setShowConfirmDialog(false)}
              disabled={acceptMutation.isPending}
            >
              Cancel
            </Button>
            <Button
              onClick={confirmAccept}
              disabled={acceptMutation.isPending}
            >
              {acceptMutation.isPending ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Accepting...
                </>
              ) : (
                <>
                  <CheckCircle2 className="h-4 w-4 mr-2" />
                  Accept Recommendation
                </>
              )}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}

