'use client';

import { useState, useEffect, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { trpc } from '@/lib/trpc/trpc';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  Sparkles, 
  User, 
  Building2, 
  TrendingUp, 
  X, 
  CheckCircle2,
  Loader2,
  AlertCircle,
  RefreshCw,
  Clock,
  Users,
  Shuffle
} from 'lucide-react';
import { toast } from 'sonner';
import { MentorRecommendationCard } from './MentorRecommendationCard';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';

interface RecommendedMentorsCardProps {
  onDismiss?: () => void;
}

export function RecommendedMentorsCard({ onDismiss }: RecommendedMentorsCardProps) {
  const router = useRouter();
  const [selectedMentorId, setSelectedMentorId] = useState<string | null>(null);
  const [showConfirmDialog, setShowConfirmDialog] = useState(false);

  // Track if we've already attempted auto-generation
  const hasAutoGenerated = useRef(false);

  // Fetch recommendations
  const { 
    data: recommendations, 
    isLoading, 
    refetch 
  } = trpc.mentorship.getRecommendedMentors.useQuery(undefined, {
    refetchOnWindowFocus: false,
    retry: 2,
  });

  // Mutations
  const acceptMutation = trpc.mentorship.acceptRecommendation.useMutation({
    onSuccess: () => {
      toast.success('Recommendation accepted! We\'ll notify the mentor.');
      router.push('/mentorship/dashboard');
    },
    onError: (error) => {
      toast.error(`Failed to accept recommendation: ${error.message}`);
    },
  });

  const dismissMutation = trpc.mentorship.dismissRecommendation.useMutation({
    onSuccess: () => {
      toast.success('Recommendations dismissed');
      onDismiss?.();
      refetch();
    },
    onError: (error) => {
      toast.error(`Failed to dismiss: ${error.message}`);
    },
  });

  const generateMutation = trpc.mentorship.generateRecommendations.useMutation({
    onSuccess: () => {
      setTimeout(() => {
        refetch();
      }, 2000);
    },
    onError: (error) => {
      console.warn('Auto-generation failed:', error.message);
    },
  });

  // Auto-generate recommendations when component loads and no recommendations exist
  useEffect(() => {
    if (
      !isLoading &&
      !recommendations &&
      !hasAutoGenerated.current &&
      !generateMutation.isPending
    ) {
      hasAutoGenerated.current = true;
      generateMutation.mutate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isLoading, recommendations]);

  const handleAccept = (mentorId: string) => {
    if (!recommendations?.id) return;
    
    setSelectedMentorId(mentorId);
    setShowConfirmDialog(true);
  };

  const confirmAccept = () => {
    if (!selectedMentorId || !recommendations?.id) return;
    
    acceptMutation.mutate({
      recommendation_id: recommendations.id,
      mentor_id: selectedMentorId,
    });
    
    setShowConfirmDialog(false);
  };

  const handleDismiss = () => {
    if (!recommendations?.id) return;
    
    if (confirm('Are you sure you want to dismiss these recommendations? You can generate new ones.')) {
      dismissMutation.mutate({
        recommendation_id: recommendations.id,
      });
    }
  };

  const handleGenerate = () => {
    generateMutation.mutate();
  };

  // Loading state
  if (isLoading || (generateMutation.isPending && !recommendations)) {
    return (
      <Card className="border-2 border-dashed border-[#500000]/20 bg-gradient-to-br from-[#500000]/5 to-transparent">
        <CardContent className="py-16">
          <div className="text-center">
            <div className="w-16 h-16 mx-auto mb-4 rounded-2xl bg-gradient-to-br from-[#500000] to-[#800000] flex items-center justify-center shadow-lg animate-pulse">
              <Sparkles className="h-8 w-8 text-white" />
            </div>
            <h3 className="text-lg font-semibold mb-2">Finding Your Perfect Mentors</h3>
            <p className="text-sm text-muted-foreground mb-4">
              {generateMutation.isPending 
                ? 'Analyzing your profile to find the best matches...' 
                : 'Loading recommendations...'}
            </p>
            <Loader2 className="h-6 w-6 animate-spin text-[#500000] mx-auto" />
          </div>
        </CardContent>
      </Card>
    );
  }

  // No recommendations state
  if (!recommendations) {
    return (
      <Card className="border-2 border-dashed border-[#500000]/20">
        <CardContent className="py-12">
          <div className="text-center">
            <div className="w-16 h-16 mx-auto mb-4 rounded-2xl bg-muted flex items-center justify-center">
              <Users className="h-8 w-8 text-muted-foreground" />
            </div>
            <h3 className="text-lg font-semibold mb-2">No Recommendations Yet</h3>
            <p className="text-sm text-muted-foreground mb-6 max-w-md mx-auto">
              {generateMutation.isError
                ? 'We couldn\'t generate recommendations right now. Please try again or complete your profile with more details.'
                : 'Let us find mentors who match your interests and goals.'}
            </p>
            <Button 
              onClick={handleGenerate} 
              disabled={generateMutation.isPending}
              className="bg-[#500000] hover:bg-[#6b0000]"
            >
              {generateMutation.isPending ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Finding Matches...
                </>
              ) : (
                <>
                  <Sparkles className="h-4 w-4 mr-2" />
                  Find My Mentors
                </>
              )}
            </Button>
          </div>
        </CardContent>
      </Card>
    );
  }

  // Has recommendations
  const { mentors } = recommendations;

  if (!mentors || mentors.length === 0) {
    return (
      <Card className="border-2 border-dashed border-[#500000]/20">
        <CardContent className="py-12">
          <div className="text-center">
            <div className="w-16 h-16 mx-auto mb-4 rounded-2xl bg-muted flex items-center justify-center">
              <AlertCircle className="h-8 w-8 text-muted-foreground" />
            </div>
            <h3 className="text-lg font-semibold mb-2">No Mentors Available</h3>
            <p className="text-sm text-muted-foreground mb-6">
              We couldn&apos;t find available mentors at this time. Please try again later.
            </p>
            <Button 
              onClick={handleGenerate} 
              disabled={generateMutation.isPending}
              variant="outline"
            >
              {generateMutation.isPending ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Searching...
                </>
              ) : (
                <>
                  <RefreshCw className="h-4 w-4 mr-2" />
                  Try Again
                </>
              )}
            </Button>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <>
      <div className="space-y-4">
        {/* Header Card */}
        <Card className="bg-gradient-to-r from-[#500000] to-[#6b0000] text-white border-0 overflow-hidden">
          <CardContent className="p-6">
            <div className="flex items-start justify-between">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-xl bg-white/10 backdrop-blur flex items-center justify-center">
                  <Sparkles className="h-6 w-6" />
                </div>
                <div>
                  <h3 className="text-xl font-bold">Recommended Mentors</h3>
                  <p className="text-white/80 text-sm">
                    We found {mentors.length} great {mentors.length === 1 ? 'match' : 'matches'} based on your profile
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleGenerate}
                  disabled={generateMutation.isPending}
                  className="text-white/80 hover:text-white hover:bg-white/10"
                  title="Get new recommendations"
                >
                  {generateMutation.isPending ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : (
                    <Shuffle className="h-4 w-4" />
                  )}
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleDismiss}
                  disabled={dismissMutation.isPending}
                  className="text-white/80 hover:text-white hover:bg-white/10"
                  title="Dismiss all"
                >
                  <X className="h-4 w-4" />
                </Button>
              </div>
            </div>
            
            {/* Expiration notice */}
            {recommendations.expires_at && (
              <div className="mt-4 pt-4 border-t border-white/20 flex items-center gap-2 text-white/70 text-sm">
                <Clock className="h-4 w-4" />
                <span>Expires {new Date(recommendations.expires_at).toLocaleDateString()}</span>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Mentor Cards Grid */}
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {mentors.map((mentor, index) => (
            <MentorRecommendationCard
              key={mentor.id}
              mentor={mentor}
              rank={index + 1}
              onSelect={() => handleAccept(mentor.id)}
              isLoading={acceptMutation.isPending && selectedMentorId === mentor.id}
            />
          ))}
        </div>

        {/* Alternative action */}
        <div className="text-center pt-2">
          <Button
            variant="link"
            className="text-muted-foreground hover:text-[#500000]"
            onClick={() => router.push('/mentorship/dashboard')}
          >
            Can&apos;t find a good match? Request a different mentor
          </Button>
        </div>
      </div>

      {/* Confirmation Dialog */}
      <Dialog open={showConfirmDialog} onOpenChange={setShowConfirmDialog}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <CheckCircle2 className="h-5 w-5 text-[#500000]" />
              Confirm Selection
            </DialogTitle>
            <DialogDescription>
              Are you sure you want to select this mentor? We&apos;ll send them a request and notify you when they respond.
            </DialogDescription>
          </DialogHeader>
          <div className="flex gap-3 justify-end mt-4">
            <Button
              variant="outline"
              onClick={() => setShowConfirmDialog(false)}
              disabled={acceptMutation.isPending}
            >
              Cancel
            </Button>
            <Button
              onClick={confirmAccept}
              disabled={acceptMutation.isPending}
              className="bg-[#500000] hover:bg-[#6b0000]"
            >
              {acceptMutation.isPending ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Sending Request...
                </>
              ) : (
                <>
                  <CheckCircle2 className="h-4 w-4 mr-2" />
                  Confirm Selection
                </>
              )}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
